// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJmWv7tEDfTHGvopmhVvOAlFFTipvH9cg',
    appId: '1:340371444506:web:c74e929df5c2454c5b52a3',
    messagingSenderId: '340371444506',
    projectId: 'vistorias-imovel',
    authDomain: 'vistorias-imovel.firebaseapp.com',
    storageBucket: 'vistorias-imovel.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSognfy_f2B-_MqRLKixjVQQ0Ca3l7k7w',
    appId: '1:340371444506:android:8bb8bc73e33719985b52a3',
    messagingSenderId: '340371444506',
    projectId: 'vistorias-imovel',
    storageBucket: 'vistorias-imovel.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAp04m5ENMLngNIx7Xicv9Q7cuaJio2rU0',
    appId: '1:340371444506:ios:75b1d69e2ccdd6975b52a3',
    messagingSenderId: '340371444506',
    projectId: 'vistorias-imovel',
    storageBucket: 'vistorias-imovel.firebasestorage.app',
    iosBundleId: 'br.com.vistoria.vistoriaImoveis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAp04m5ENMLngNIx7Xicv9Q7cuaJio2rU0',
    appId: '1:340371444506:ios:75b1d69e2ccdd6975b52a3',
    messagingSenderId: '340371444506',
    projectId: 'vistorias-imovel',
    storageBucket: 'vistorias-imovel.firebasestorage.app',
    iosBundleId: 'br.com.vistoria.vistoriaImoveis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJmWv7tEDfTHGvopmhVvOAlFFTipvH9cg',
    appId: '1:340371444506:web:a2e4ff77d953cd465b52a3',
    messagingSenderId: '340371444506',
    projectId: 'vistorias-imovel',
    authDomain: 'vistorias-imovel.firebaseapp.com',
    storageBucket: 'vistorias-imovel.firebasestorage.app',
  );
}
